[Interface]
# Bouncing = 12
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = GMxuSAd6VYJHNcCC12MeN8DUCZ+TbBdNaMweXi0+5Go=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# AU#13
PublicKey = 8kyi2e0ziUqhs+ooJYYI0yaVhv/bneUC1fhV5X2q/SE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.33.236:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:db0a:2333::10]:51820
PersistentKeepalive = 25