[Interface]
# Bouncing = 3
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = cOsw/1oS8t0Re6kmJZXSbqirAG64BoL6ZMuEDiiSTV8=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# AU#17
PublicKey = KIm+13jfrrbXNPqYpd+WaWnCrgubWaSQnj8xn1Od8Fk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 138.199.33.225:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:db0a:2334::10]:51820
PersistentKeepalive = 25